spring.application.name=pedroplex

# Increase buffer size for large API responses
spring.codec.max-in-memory-size=1048576

# API URLs (defaults)
trakt.api.url=https://api.trakt.tv
tmdb.api.url=https://api.themoviedb.org/3
